### PR TITLE
updated INSTALL.md with xampp and source code information

### PR DESCRIPTION
**Pull request by larry2e**
How to install source code and XAMPP

### CODE REVIEW

**Comment by lazar-parker** [comment]
The install documents contains the instructions necessary to teach any user how to download, install, and start xampp, as well as all necessary source code for running the app

**Comment by ryanMan1848** [comment]
Install document tell us how to install and run XAMPP and how to download the sourcecode and where to place it so that we can run it when we are using XAMPP.

**Comment by ParkerAllen** [comment]
Install and run XAMPP is contained in Install document. Contain source code necessary for app running as well.

**Comment by StickyKeysEnabled** [comment]
The download and XAMPP information is all accurate. May need update when standard test case procedure and file paths are determined.

**Comment by Acalvinm** [comment]
The install document has detailed steps to download, install, and then run XAMPP,

**Pull request merged**
