### PR TITLE
Reorganizing

### PR DESCRIPTION
**Pull request by Acalvinm**
The project structure has followed a standard set on the Organize Your Next PHP Project the Right Way page https://code.tutsplus.com/tutorials/organize-your-next-php-project-the-right-way--net-5873 .  It has the app folder as public and the server folder as resources.

### CODE REVIEW

**Comment by ryanMan1848** [comment]
Server folder will be in a separate folder than app and will contain all MySQL back-end database work and code. - Ryan Willox

**Comment by Acalvinm** [comment]
Alicia Calvin-McNeal - The images folder is for holding images.

**Comment by lazar-parker** [comment]
The App folder holds all files relevant to the user-end experience, including all pages users interact with while using the app - Parker Lazar

**Comment by StickyKeysEnabled** [comment]
The js folder holds any scripts the client may need to run. -Alex Crawford

**Comment by ParkerAllen** [comment]
The CSS folder will hold the code that make our webpages look good - Parker Allen

**Comment by larry2e** [comment]
The .git folder contains all information regarding the git version control which allows us to keep track of our commit and branch history. -Lawrence Straughter

**Pull request merged**
